version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  
  api:
    build:
      context: ./api
      args:
        RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    ports:
      - "3000:3000"
    depends_on:
      - redis
    volumes:
      - ./api:/rails
    environment:
      REDIS_URL: "asdf"
      OPENAI_API_KEY: "asdf"
