enabled: true
name: summaryai/api
image: :image
port: 3000
healthChecks:
  readiness:
    path: /health/index
  liveness:
    path: /health/index
resources:
  replicas: 1
  instanceType: C4
  autoscaling:
    enabled: false
    maxReplicas: 2
    metrics:
      - metric: cpu
        summary: average
        value: 30