enabled: true
name: summaryai/api
image: :image
port: 3000
env:
  - name: REDIS_URL
    value: secret:REDIS_URL
healthChecks:
  readiness:
    path: /health
resources:
  replicas: 1
  instanceType: C4
  autoscaling:
    enabled: true
    maxReplicas: 2
    metrics:
      - metric: cpu
        summary: average
        value: 30