name: master
on:
  push:
    branches:
      - master

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: release-drafter.yaml
          publish: true
