name: Main

on:
  push:
    tags:
      - summaryai@*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set docker tag name
        run: echo "::set-output name=DOCKER_TAG_NAME::$(echo $GITHUB_REF | cut -d / -f 3 | sed 's/summaryai@//')"
        id: docker-tag-name

      - name: Set up docker build
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: api
          file: ./api/Dockerfile
          push: true
          tags: |
            brodeynewman/summaryai:${{ steps.docker-tag-name.outputs.DOCKER_TAG_NAME }}
          build-args: |
            RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}

      - uses: paperspace/deploy-action@v1.0
        name: Deploy API
        id: deploy
        env:
          PAPERSPACE_API_KEY: ${{ secrets.PAPERSPACE_API_KEY }}
        with:
          projectId: pq0q1mtej9w
          configPath: .paperspace/config.yaml
          image: brodeynewman/summaryai:${{ steps.docker-tag-name.outputs.DOCKER_TAG_NAME }}

      - name: Node setup
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.2

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: npm install
        working-directory: ./web
        run: npm i
      
      - name: build
        working-directory: ./web
        run: npm run build
      
      - name: copy files to s3
        working-directory: ./web
        run: aws s3 sync ./out s3://summary.ai

      - name: Invalidate cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E23ULCPET9PKHO \
            --paths "/*"