name: Main

on:
  push:
    branches: [master] # the branch we want this to run on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Node setup
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: npm install
        working-directory: ./web
        run: npm i
      
      - name: build
        working-directory: ./web
        run: npm run build
      
      - name: copy files to s3
        working-directory: ./web
        run: aws s3 sync ./out s3://summary.ai

      - name: Invalidate cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E23ULCPET9PKHO \
            --paths "/*"